[Interface]
# Key for lovefield-qb
# Bouncing = 20
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = SLVmPuUNKLc9XtO7VD2QtcedfE2NnB/V1OMH3wuxqEc=
# Address = 10.2.0.2/32, 2a07:b944::2:2/128
# DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# US-TX#83
PublicKey = dJWLpQaWP1hw0QLQW84B++fWtopgneOafYVZXyyUoAM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.217.66:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:9a:64::10]:51820
PersistentKeepalive = 25